export const translationResources = {
  en: { translation: { "auth.login": "Login", "onboarding.selectLanguage": "Select your Language", "wallet.withdrawLocked": "Withdrawals Locked", "chatbot.help": "How can I help you?", "legal.privacy": "Privacy Policy" } },
  hi: { translation: { "auth.login": "लॉग इन करें", "onboarding.selectLanguage": "अपनी भाषा चुनें", "wallet.withdrawLocked": "निकासी लॉक है", "chatbot.help": "मैं आपकी कैसे मदद कर सकता हूँ?", "legal.privacy": "गोपनीयता नीति" } },
  ta: { translation: { "auth.login": "உள்நுழை", "onboarding.selectLanguage": "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்", "wallet.withdrawLocked": "திரும்பப் பெறுதல் பூட்டப்பட்டுள்ளது", "chatbot.help": "நான் உங்களுக்கு எப்படி உதவ முடியும்?", "legal.privacy": "தனியுரிமை கொள்கை" } },
  te: { translation: { "auth.login": "లాగిన్", "onboarding.selectLanguage": "మీ భాషను ఎంచుకోండి", "wallet.withdrawLocked": "ఉపసంహరణలు లాక్ చేయబడ్డాయి", "chatbot.help": "నేను మీకు ఎలా సహాయపడగలను?", "legal.privacy": "గోప్యతా విధానం" } },
  bn: { translation: { "auth.login": "লগইন", "onboarding.selectLanguage": "আপনার ভাষা নির্বাচন করুন", "wallet.withdrawLocked": "প্রত্যাহার লক করা আছে", "chatbot.help": "আমি আপনাকে কিভাবে সাহায্য করতে পারি?", "legal.privacy": "গোপনীয়তা নীতি" } },
  mr: { translation: { "auth.login": "लॉगिन", "onboarding.selectLanguage": "तुमची भाषा निवडा", "wallet.withdrawLocked": "पैसे काढणे लॉक केले आहे", "chatbot.help": "मी तुम्हाला कशी मदत करू शकेन?", "legal.privacy": "गोपनीयता धोरण" } },
  kn: { translation: { "auth.login": "ಲಾಗಿನ್", "onboarding.selectLanguage": "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ", "wallet.withdrawLocked": "ಹಿಂತೆಗೆದುಕೊಳ್ಳುವಿಕೆಗಳನ್ನು ಲಾಕ್ ಮಾಡಲಾಗಿದೆ", "chatbot.help": "ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?", "legal.privacy": "ಗೌಪ್ಯತಾನೀತಿ" } },
  ml: { translation: { "auth.login": "ലോഗിൻ", "onboarding.selectLanguage": "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക", "wallet.withdrawLocked": "പിൻവലിക്കലുകൾ പൂട്ടിയിരിക്കുന്നു", "chatbot.help": "നിങ്ങളെ എങ്ങനെ സഹായിക്കാൻ കഴിയും?", "legal.privacy": "സ്വകാര്യതാ നയം" } },
  gu: { translation: { "auth.login": "લૉગિન", "onboarding.selectLanguage": "તમારી ભાષા પસંદ કરો", "wallet.withdrawLocked": "ઉપાડ લૉક છે", "chatbot.help": "હું તમને કેવી રીતે મદદ કરી શકું?", "legal.privacy": "ગોપનીયતા નીતિ" } },
  pa: { translation: { "auth.login": "ਲਾਗਿਨ", "onboarding.selectLanguage": "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ", "wallet.withdrawLocked": "ਕਢਵਾਉਣਾ ਲਾਕ ਹੈ", "chatbot.help": "ਮੈਂ ਤੁਹਾਡੀ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?", "legal.privacy": "ਪਰਦੇਦਾਰੀ ਨੀਤੀ" } }
};
